services:
  album-manager:
    build: .
    container_name: immich_album_manager

    ports:
      - "5055:5050"

    volumes:
      - ./config:/config
      - ./logs:/logs
      - /share/Multimedia:/external:ro

      # Family Photo Importer
      - /share/Container/family-photo-importer:/family-photo-importer:ro

      # Ergebnis des Family Photo Importers
      - /share/Container/family-photo-importer/reports:/import-reports:rw

      # Zugriff auf Docker Engine des QNAP-Hosts
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped

    networks:
      - default
      - immich

networks:
  immich:
    external: true
    name: immich_default